### ISSUE TITLE
Print statement outputting `1`'s and `0`'s is not clear

### ISSUE THREAD

**Issue by callumfrance** [callumfrance/conway#16]
At the moment the board is being printed like so -
```
+ - - - - - +
| 0 0 0 0 0 |
| 0 0 1 0 0 |
| 0 1 1 1 0 |
| 0 0 1 0 0 |
| 0 0 0 0 0 |
+ - - - - - +
```

It is a little hard to read the `1`'s separately from the zeros.
It would be better to use differently-sized characters to represent cells.

e.g. alive cells could be `@` and dead cells could be `.`

```
+ - - - - - +
| . . . . . |
| . . @ . . |
| . @ @ @ . |
| . . @ . . |
| . . . . . |
+ - - - - - +
```

As you can clearly see, this is way easier to read.

**Comment by RaulFernandezNavarro** [comment]
Hey, I am interested in this issue. Is it still open?

**Comment by RaulFernandezNavarro** [comment]
Done!
